### ISSUE TITLE
Rename to Codocs / CODOCS

### ISSUE THREAD

**Issue by dmonad** [y-js/codocs#1]

**Comment by istvank** [comment]
What's the current name? Is it CODOCS? or CoDocs (personally preferring that) or even CoDoCs? Or is it cOdOcS? 💃

**Comment by dmonad** [comment]
I prefer [CO**DOCS**](). I like how most of the letters look like an O. Also, it looks really cool as a headline.  If you prefer it, you can also write [Codocs](). I personally dislike camel case in in product names.
