### ISSUE TITLE
codocs.y-js.org has no content

### ISSUE THREAD

**Issue by marcelklehr** [y-js/codocs#8]
Even after signing in with google I get only a heading reading "Home". Am I missing something or is there merely nothing, as of yet?

**Comment by dmonad** [comment]
That's weird. Does it work on [codocs.dmonad.io/](https://codocs.dmonad.io/)? If not, can you state browser, browser version & log messages?

**Comment by marcelklehr** [comment]
Chromium 55.0.2883.87 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
```
y.js:1 The regenerator/runtime module is deprecated; please import regenerator-runtime/runtime instead.
n.3.regenerator-runtime/runtime @ y.js:1
2434017003-idpiframe.js:12 Uncaught DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
    at x.C (https://ssl.gstatic.com/accounts/o/2434017003-idpiframe.js:12:285)
    at Object.k.vb (https://ssl.gstatic.com/accounts/o/2434017003-idpiframe.js:8:121)
    at S.h.start (https://ssl.gstatic.com/accounts/o/2434017003-idpiframe.js:50:170)
    at Object.Bb [as startIdpIFrame] (https://ssl.gstatic.com/accounts/o/2434017003-idpiframe.js:84:713)
    at https://accounts.google.com/o/oauth2/iframe:1:414
service-worker.js:1 Service Worker termination by a timeout timer was canceled because DevTools is attached.
```

It doesn't work on codocs.dmonad.io either.

**Comment by dmonad** [comment]
You probably disallowed third-party cookies. [Read this](https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document). This is required by the authentification library I'm using.

Try [codocs.dmonad.io](https://codocs.dmonad.io) again

**Comment by marcelklehr** [comment]
Ahh, makes sense. It works now. Thank you. Looks good!
